import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    nav: {
      company: 'Company',
      companyHistory: 'Company History',
      employees: 'Employees',
      services: 'Services',
      objects: 'Properties',
      associations: 'Associations',
      bvi: 'BVI',
      vdiv: 'VDIV',
      forms: 'Forms',
      damageReport: 'Damage Report',
      keyOrder: 'Key Order',
      tenantChange: 'Tenant Change',
      customerPortal: 'Customer Portal',
      contact: 'Contact',
    },
    hero: {
      badge: 'Your Property Manager',
      title: 'WERT Property Management',
      subtitle: 'Property Management That Works',
      bullets: [
        'We take care of managing your property – so you dont have to worry about a thing.',
        'We work in a structured, accessible, and solution-oriented manner.',
        'No complicated processes – just clear responsibilities and fast results.',
        'Direct communication – Fast response times – Transparent processes',
      ],
      ctaContact: 'Get In Touch',
      ctaServices: 'Our Services',
    },
    stats: { years: 'Years Experience', gen: 'Generations', objects: 'Managed Properties', satisfaction: 'Owner Satisfaction' },
    about: {
      tag: 'Why Choose Us?',
      title: 'WERT — Professionals in Property Management',
      p1: 'Looking for management for your property? You\'ve come to the right place! We are professionals in property management — and have been for more than 55 years, now in the third generation.',
      p2: 'Our goal is to provide property management that guarantees the highest satisfaction of our owners and not only maintains but also improves the value of the buildings we manage.',
      points: ['Over 55 years of experience', 'Family business in third generation', 'Personal and individual support', 'Member of BVI and VDIV'],
      ctaHistory: 'Company History',
      ctaTeam: 'Meet the Team',
    },
    services: {
      tag: 'What We Offer',
      title: 'Our Services',
      subtitle: 'Comprehensive property management services tailored to your needs — everything from one expert source.',
      learnMore: 'Learn More',
      ctaAll: 'All Services',
      items: [
        // {
        //   title: 'Residential Property Management',
        //   desc: 'We provide comprehensive management for apartment buildings and private properties – from billing to tenant support.',
        //   bullets: [],
        // },
        // {
        //   title: 'Commercial Property Management',
        //   desc: 'Management of office, retail, and commercial properties with a focus on efficiency, structure, and smooth operations.',
        //   bullets: [],
        // },
        {
          title: 'WEG Management',
          desc: '',
          bullets: ['Organization of owners meetings', 'Budget planning and annual financial statements', 'Implementation of resolutions', 'Maintenance planning', 'Management of service providers', 'Transparent communication with owners'],
        },
        {
          title: 'Individual Unit Management',
          desc: '',
          bullets: ['Tenant relations', 'Rent collection and dunning', 'Service charge accounting', 'Commissioning and supervision of repairs', 'Apartment handovers', 'Regular reports for owners'],
        },
        {
          title: 'Rental Management',
          desc: '',
          bullets: ['Marketing of vacant apartments', 'Credit checks for new tenants', 'Drafting of lease agreements', 'Ongoing management of the tenancy', 'Rent increases in accordance with statutory regulations', 'Management of lease terminations and handovers'],
        },
      ],
    },
    objects: {
      tag: 'Portfolio',
      title: 'Overview of Our Properties',
      subtitle: 'A selection of the residential and commercial properties currently under our management.',
      allObjects: 'All Properties',
      units: 'Units',
      viewDetails: 'View Details',
    },
    contactCTA: {
      tag: 'Contact',
      title: 'Get in Touch With Us',
      desc: 'Do you need support managing a property? Contact us — we would be happy to advise you personally and without obligation.',
      phone: 'Phone',
      email: 'Email',
      address: 'Address',
      formTitle: 'Online Contact Form',
      firstName: 'First Name',
      lastName: 'Last Name',
      phoneFld: 'Phone',
      subject: 'Subject',
      message: 'Your Message',
      send: 'Send Message',
      sending: 'Sending...',
      success: 'Thank you! Your message has been sent successfully.',
      error: 'Something went wrong. Please try again.',
    },
    bvi: {
      tag: 'Professional Association',
      title: 'Ten Principles for BVI Property Managers',
      desc: 'Quality standards and binding codes of conduct create competitive advantages. A code that brings together and helps in conflicts.',
      link: 'The Ten Professional Principles',
    },
    footer: {
      desc: 'Your reliable partner for professional property management for over 55 years.',
      navigation: 'Navigation',
      legal: 'Legal',
      links: { impressum: 'Imprint', datenschutz: 'Privacy Policy', info: 'Information Obligations', verfahren: 'Public Processing Register' },
      portal: 'Customer Portal Login',
      rights: 'All rights reserved.',
    },
    pages: {
      company: {
        title: 'The Company',
        history: {
          tag: 'Our Story',
          title: 'Company History',
          content: '',
          milestones: [],
        },
        team: {
          tag: 'Our People',
          title: 'Our Employees',
          desc: 'Our experienced team is your first point of contact for all questions regarding your property.',
          members: [],
        },
      },
      services: {
        tag: 'Our Services',
        title: 'Services for Property Owners',
        heroDesc: 'Comprehensive property management services — everything from one source.',
        wohnTab: 'Residential Property',
        mietTab: 'Rental Management',
      },
      objects: {
        tag: 'Our Properties',
        title: 'Properties Under Management',
        heroDesc: 'A selection of residential and commercial properties we currently manage.',
        filter: { all: 'All', apartment_complex: 'Apartment Complex', apartment_building: 'Apartment Building', commercial: 'Commercial', mixed: 'Mixed Use' },
      },
      contact: {
        tag: 'Contact',
        title: 'We Are Here For You',
        heroDesc: 'Get in touch — we look forward to hearing from you.',
        mapTitle: 'Find Us',
      },
      bvi: {
        tag: 'Professional Association',
        title: 'BVI — Federal Association',
        heroDesc: 'Quality, trust and professional standards.',
        principles: [
          'The property manager acts in the best interest of the owner community.',
          'He maintains transparent and comprehensible accounting.',
          'He ensures professional maintenance of the managed properties.',
          'He acts independently and free from conflicts of interest.',
          'He treats all owners equally and fairly.',
          'He maintains confidentiality about business affairs.',
          'He continuously trains himself and his employees.',
          'He maintains proper and complete documentation.',
          'He communicates openly and proactively with owners.',
          'He complies with all legal regulations and professional standards.',
        ],
      },
      vdiv: {
        tag: 'Professional Association',
        title: 'VDIV — Association of German Property Managers',
        heroDesc: 'Professional representation of the property management sector.',
      },
      forms: {
        damage: {
          tag: 'Forms',
          title: 'Damage Report',
          heroDesc: 'Report damage or defects in your property.',
          nameFld: 'Full Name', emailFld: 'Email', phoneFld: 'Phone', addressFld: 'Property Address',
          unitFld: 'Unit/Apartment', damageTypeFld: 'Type of Damage', descFld: 'Description of Damage',
          urgencyFld: 'Urgency', submit: 'Submit Report', sending: 'Submitting...', success: 'Your damage report has been submitted successfully.', error: 'Error submitting. Please try again.',
          urgencyOptions: ['Low', 'Medium', 'High', 'Emergency'],
          damageTypes: ['Water Damage', 'Heating Failure', 'Electrical Issue', 'Window/Door Damage', 'Roof Damage', 'Elevator Failure', 'Pest Infestation', 'Other'],
        },
        key: {
          tag: 'Forms',
          title: 'Key Order',
          heroDesc: 'Order replacement keys for your property.',
          nameFld: 'Full Name', emailFld: 'Email', phoneFld: 'Phone', addressFld: 'Property Address',
          unitFld: 'Unit/Apartment', keyTypeFld: 'Key Type', quantityFld: 'Quantity', reasonFld: 'Reason for Order',
          submit: 'Submit Order', sending: 'Submitting...', success: 'Your key order has been submitted successfully.', error: 'Error submitting. Please try again.',
          keyTypes: ['Apartment Key', 'Mailbox Key', 'Cellar Key', 'Main Entrance Key', 'Garage Key'],
        },
        tenant: {
          tag: 'Forms',
          title: 'Tenant Change',
          heroDesc: 'Notify us of an upcoming tenant change in your property.',
          propertyFld: 'Property Address', unitFld: 'Unit/Apartment',
          outgoingTitle: 'Outgoing Tenant', incomingTitle: 'Incoming Tenant',
          tenantName: 'Tenant Name', tenantEmail: 'Email', moveOutDate: 'Move-Out Date', moveInDate: 'Move-In Date',
          ownerTitle: 'Owner Information', ownerName: 'Owner Name', ownerEmail: 'Owner Email',
          notesFld: 'Additional Notes', submit: 'Submit Notification', sending: 'Submitting...', success: 'Your tenant change notification has been submitted.', error: 'Error submitting. Please try again.',
        },
      },
    },
  },
  de: {
    nav: {
      company: 'Unternehmen',
      companyHistory: 'Firmengeschichte',
      employees: 'Mitarbeiter',
      services: 'Leistungen',
      objects: 'Objekte',
      associations: 'Fachverbände',
      bvi: 'BVI',
      vdiv: 'VDIV',
      forms: 'Formulare',
      damageReport: 'Schadensmeldung',
      keyOrder: 'Schlüsselbestellung',
      tenantChange: 'Mieterwechsel',
      customerPortal: 'Kundenportal',
      contact: 'Kontakt',
    },
    hero: {
      badge: 'Ihr Immobilienverwalter',
      title: 'WERT Immobilienverwaltung',
      subtitle: 'Immobilienverwaltung, Die Funktioniert',
      bullets: [
        'Wir kümmern uns um die Verwaltung Ihrer Immobilie – damit Sie sich um nichts kümmern müssen.',
        'Wir arbeiten strukturiert, zugänglich und lösungsorientiert.',
        'Keine komplizierten Prozesse – nur klare Verantwortlichkeiten und schnelle Ergebnisse.',
        'Direkte Kommunikation – Kurze Reaktionszeiten – Transparente Prozesse',
      ],
      ctaContact: 'Jetzt Kontakt aufnehmen',
      ctaServices: 'Unsere Leistungen',
    },
    stats: { years: 'Jahre Erfahrung', gen: 'Generationen', objects: 'Verwaltete Objekte', satisfaction: 'Eigentümerzufriedenheit' },
    about: {
      tag: 'Warum wir?',
      title: 'WERT — Die Profis in der Immobilienverwaltung',
      p1: 'Sie suchen eine Verwaltung für Ihre Immobilie? Dann sind Sie bei uns richtig! In Sachen Immobilienverwaltung sind wir Profis — und das bereits seit mehr als 55 Jahren in der dritten Generation.',
      p2: 'Unser Bestreben ist es, eine Immobilienverwaltung zu gewährleisten, die höchste Zufriedenheit unserer Eigentümer garantiert und nicht nur eine Werterhaltung, sondern auch eine Wertverbesserung der von uns betreuten Gebäude sichert.',
      points: ['Über 55 Jahre Erfahrung', 'Familienbetrieb in dritter Generation', 'Persönliche und individuelle Betreuung', 'Mitglied im BVI und VDIV'],
      ctaHistory: 'Firmengeschichte',
      ctaTeam: 'Unser Team',
    },
    services: {
      tag: 'Was wir anbieten',
      title: 'Unsere Leistungen',
      subtitle: 'Umfassende Immobilienverwaltungsleistungen – alles aus einer kompetenten Hand.',
      learnMore: 'Mehr erfahren',
      ctaAll: 'Alle Leistungen',
      items: [
        // {
        //   title: 'Wohnimmobilienverwaltung',
        //   desc: 'Wir bieten umfassende Verwaltung für Mehrfamilienhäuser und Privatimmobilien – von der Abrechnung bis zur Mieterbetreuung.',
        //   bullets: [],
        // },
        // {
        //   title: 'Gewerbeimmobilienverwaltung',
        //   desc: 'Verwaltung von Büro-, Einzel- und Gewerbeobjekten mit Fokus auf Effizienz, Struktur und reibungslosen Betrieb.',
        //   bullets: [],
        // },
        {
          title: 'WEG-Verwaltung',
          desc: '',
          bullets: ['Organisation der Eigentümerversammlungen', 'Wirtschaftsplan und Jahresabrechnung', 'Umsetzung von Beschlüssen', 'Instandhaltungsplanung', ' Betreuung von Dienstleistern', 'Transparente Kommunikation mit Eigentümern'],
        },
        {
          title: 'Sondereigentumsverwaltung',
          desc: '',
          bullets: ['Mieterbetreuung', 'Mietinkasso und Mahnwesen', 'Betriebskostenabrechnung', 'Beauftragung und Überwachung von Reparaturen', 'Wohnungsübergaben und -abnahmen', 'Regelmäßige Berichte für Eigentümer'],
        },
        {
          title: 'Mietverwaltung',
          desc: '',
          bullets: ['Vermarktung freier Wohnungen', 'Bonitätsprüfung neuer Mieter', 'Erstellung von Mietverträgen', 'Laufende Betreuung des Mietverhältnisses', 'Mieterhöhungen nach den gesetzlichen Vorgaben', 'Kündigungs- und Übergabemanagement'],
        },
      ],
    },
    objects: {
      tag: 'Portfolio',
      title: 'Einblick in unsere Objekte',
      subtitle: 'Eine Auswahl der Wohn- und Gewerbeimmobilien, die wir derzeit verwalten.',
      allObjects: 'Alle Objekte',
      units: 'Einheiten',
      viewDetails: 'Details ansehen',
    },
    contactCTA: {
      tag: 'Kontakt',
      title: 'Kontakt zu uns aufnehmen',
      desc: 'Sie benötigen Unterstützung bei der Verwaltung einer Immobilie? Nehmen Sie Kontakt zu uns auf — wir beraten Sie gerne persönlich und unverbindlich.',
      phone: 'Telefon',
      email: 'E-Mail',
      address: 'Adresse',
      formTitle: 'Online Kontaktformular',
      firstName: 'Vorname',
      lastName: 'Nachname',
      phoneFld: 'Telefon',
      subject: 'Betreff',
      message: 'Ihre Nachricht',
      send: 'Nachricht senden',
      sending: 'Wird gesendet...',
      success: 'Vielen Dank! Ihre Nachricht wurde erfolgreich gesendet.',
      error: 'Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.',
    },
    bvi: {
      tag: 'Fachverband',
      title: 'Zehn Grundsätze für BVI-Immobilienverwalter',
      desc: 'Qualitative Standards und verbindliche Verhaltensregeln schaffen Wettbewerbsvorteile am Markt. Ein Kodex, der zusammenführt und in Konflikten hilft.',
      link: 'Die zehn Berufsgrundsätze',
    },
    footer: {
      desc: 'Ihr verlässlicher Partner für professionelle Immobilienverwaltung seit über 55 Jahren.',
      navigation: 'Navigation',
      legal: 'Rechtliches',
      links: { impressum: 'Impressum', datenschutz: 'Datenschutz', info: 'Informationspflicht', verfahren: 'Öffentliches Verfahrensverzeichnis' },
      portal: 'Login Kundenportal',
      rights: 'Alle Rechte vorbehalten.',
    },
    pages: {
      company: {
        title: 'Das Unternehmen',
        history: {
          tag: 'Unsere Geschichte',
          title: 'Firmengeschichte',
          content: '',
          milestones: [],
        },
        team: {
          tag: 'Unser Team',
          title: 'Unsere Mitarbeiter',
          desc: 'Unser erfahrenes Team ist Ihr erster Ansprechpartner für alle Fragen rund um Ihre Immobilie.',
          members: [],
        },
      },
      services: {
        tag: 'Unsere Leistungen',
        title: 'Leistungen für Eigentümer',
        heroDesc: 'Umfassende Immobilienverwaltungsleistungen — alles aus einer Hand.',
        wohnTab: 'Wohnungseigentum',
        mietTab: 'Mietverwaltung',
      },
      objects: {
        tag: 'Unsere Objekte',
        title: 'Verwaltete Objekte',
        heroDesc: 'Eine Auswahl der Wohn- und Gewerbeimmobilien, die wir derzeit verwalten.',
        filter: { all: 'Alle', apartment_complex: 'Wohnanlage', apartment_building: 'Mehrfamilienhaus', commercial: 'Gewerbe', mixed: 'Gemischt' },
      },
      contact: {
        tag: 'Kontakt',
        title: 'Wir sind für Sie da',
        heroDesc: 'Nehmen Sie Kontakt auf — wir freuen uns auf Ihre Nachricht.',
        mapTitle: 'So finden Sie uns',
      },
      bvi: {
        tag: 'Fachverband',
        title: 'BVI — Bundesfachverband',
        heroDesc: 'Qualität, Vertrauen und professionelle Standards.',
        principles: [
          'Der Immobilienverwalter handelt im besten Interesse der Eigentümergemeinschaft.',
          'Er führt eine transparente und nachvollziehbare Buchhaltung.',
          'Er sorgt für die fachgerechte Instandhaltung der verwalteten Objekte.',
          'Er handelt unabhängig und frei von Interessenkonflikten.',
          'Er behandelt alle Eigentümer gleich und fair.',
          'Er wahrt die Vertraulichkeit über Geschäftsangelegenheiten.',
          'Er bildet sich und seine Mitarbeiter kontinuierlich weiter.',
          'Er führt eine ordnungsgemäße und vollständige Dokumentation.',
          'Er kommuniziert offen und proaktiv mit den Eigentümern.',
          'Er hält alle gesetzlichen Vorschriften und Berufsstandards ein.',
        ],
      },
      vdiv: {
        tag: 'Fachverband',
        title: 'VDIV — Verband der Immobilienverwalter',
        heroDesc: 'Professionelle Interessenvertretung der Immobilienverwaltungsbranche.',
      },
      forms: {
        damage: {
          tag: 'Formulare',
          title: 'Schadensmeldung',
          heroDesc: 'Melden Sie Schäden oder Mängel in Ihrer Immobilie.',
          nameFld: 'Vollständiger Name', emailFld: 'E-Mail', phoneFld: 'Telefon', addressFld: 'Objektadresse',
          unitFld: 'Einheit/Wohnung', damageTypeFld: 'Art des Schadens', descFld: 'Schadensbeschreibung',
          urgencyFld: 'Dringlichkeit', submit: 'Meldung absenden', sending: 'Wird gesendet...', success: 'Ihre Schadensmeldung wurde erfolgreich übermittelt.', error: 'Fehler beim Senden. Bitte versuchen Sie es erneut.',
          urgencyOptions: ['Niedrig', 'Mittel', 'Hoch', 'Notfall'],
          damageTypes: ['Wasserschaden', 'Heizungsausfall', 'Elektrisches Problem', 'Fenster-/Türschaden', 'Dachschaden', 'Aufzugsausfall', 'Schädlingsbefall', 'Sonstiges'],
        },
        key: {
          tag: 'Formulare',
          title: 'Schlüsselbestellung',
          heroDesc: 'Bestellen Sie Ersatzschlüssel für Ihre Immobilie.',
          nameFld: 'Vollständiger Name', emailFld: 'E-Mail', phoneFld: 'Telefon', addressFld: 'Objektadresse',
          unitFld: 'Einheit/Wohnung', keyTypeFld: 'Schlüsselart', quantityFld: 'Anzahl', reasonFld: 'Begründung',
          submit: 'Bestellung absenden', sending: 'Wird gesendet...', success: 'Ihre Schlüsselbestellung wurde erfolgreich übermittelt.', error: 'Fehler beim Senden. Bitte versuchen Sie es erneut.',
          keyTypes: ['Wohnungsschlüssel', 'Briefkastenschlüssel', 'Kellerschlüssel', 'Hauseingangsschlüssel', 'Garagenschlüssel'],
        },
        tenant: {
          tag: 'Formulare',
          title: 'Mieterwechsel',
          heroDesc: 'Informieren Sie uns über einen bevorstehenden Mieterwechsel.',
          propertyFld: 'Objektadresse', unitFld: 'Einheit/Wohnung',
          outgoingTitle: 'Ausziehender Mieter', incomingTitle: 'Einziehender Mieter',
          tenantName: 'Name des Mieters', tenantEmail: 'E-Mail', moveOutDate: 'Auszugsdatum', moveInDate: 'Einzugsdatum',
          ownerTitle: 'Eigentümerinformationen', ownerName: 'Name des Eigentümers', ownerEmail: 'E-Mail des Eigentümers',
          notesFld: 'Zusätzliche Hinweise', submit: 'Meldung absenden', sending: 'Wird gesendet...', success: 'Ihre Mieterwechselmeldung wurde erfolgreich übermittelt.', error: 'Fehler beim Senden. Bitte versuchen Sie es erneut.',
        },
      },
    },
  },
};

const LangContext = createContext();

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState('de');
  const t = translations[lang];
  const toggleLang = () => setLang(l => l === 'en' ? 'de' : 'en');
  return <LangContext.Provider value={{ lang, toggleLang, t }}>{children}</LangContext.Provider>;
};

export const useLang = () => useContext(LangContext);
export default LangContext;